version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sakila
    volumes:
      - ./sakila-dump.sql:/docker-entrypoint-initdb.d/sakila-dump.sql
    ports:
      - "3306:3306"

  omnidb:
    image: omnidbteam/omnidb:latest
    environment:
      OMNIDB_DATABASE_USER: admin
      OMNIDB_DATABASE_PASSWORD: admin
      OMNIDB_DATABASE_PORT: 8080
    ports:
      - "8080:8000"
    depends_on:
      - db
    